FROM node:22.14-bullseye

RUN apt-get update && apt-get install -y \
    curl \
    git \
    sqlite3 \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 3000

# Create app directory, data directory, and empty .env file
WORKDIR /app
RUN mkdir -p /app/data
RUN mkdir -p /var/log
RUN touch /app/data/.env
RUN ln -s /app/data/.env /app/.env

# Install dependencies and copy application files
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm ci
COPY . ./

# `DB_PATH` is passed in during `docker build` and it sets the `DB_PATH`
# environment variable which is required for `npm run build` (buildtime
# environment var) and `npm start` (runtime environment var). See
# https://www.saltycrane.com/blog/2021/04/buildtime-vs-runtime-environment-variables-nextjs-docker/#setting-dynamic-buildtime-environment-variables-that-are-available-at-runtime-also
ARG DB_PATH
ENV DB_PATH=$DB_PATH

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build
CMD ["npm", "start"]
